# Generated by Django 5.2.11 on 2026-02-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255, verbose_name='Kitabyn ady')),
                ('author', models.CharField(max_length=255, verbose_name='Awtory')),
                ('page_volume', models.IntegerField(max_length=10, verbose_name='Sahypa sany')),
                ('published_date', models.DateField(verbose_name='Neshir edilen senesi')),
            ],
            options={
                'verbose_name': 'kitap',
                'verbose_name_plural': 'kitaplar',
            },
        ),
    ]
